#!/usr/bin/env python3
"""
AI SuperComputer Demo
演示 AI 超級電腦

Showcases the key capabilities of the AI-native architecture.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from ai_primitives.function_particle import AIFunctionParticle
from ai_primitives.module_particle import AIModuleParticle
from runtime.ai_stack_runtime import AIStackRuntime, AIStack
from runtime.fusion_engine import FusionEngine
from self_modification.code_evolver import CodeEvolver


def demo_ai_particles():
    """Demo 1: AI Particles - Functions Generated by AI"""
    print("\n" + "="*70)
    print("DEMO 1: AI Particles - AI Generates Functions")
    print("="*70)
    
    print("\n📝 Creating AI function particle (no code written by human)...")
    func = AIFunctionParticle(
        function_name="calculate_fibonacci",
        description="Calculate Fibonacci number at position n",
        parameters={"n": "position in Fibonacci sequence"}
    )
    
    print("🤖 AI synthesizing function implementation...")
    code = func.synthesize()
    
    print(f"\n✅ AI Generated Code:\n{code}\n")
    
    print("🚀 Executing AI-generated function...")
    result = func(10)
    print(f"📊 Result: {result}\n")


def demo_particle_fusion():
    """Demo 2: Particle Fusion - Multiple AIs Working Together"""
    print("\n" + "="*70)
    print("DEMO 2: Particle Fusion - Multiple AIs Collaborate")
    print("="*70)
    
    print("\n🔧 Creating 3 AI particles with different providers...")
    p1 = AIFunctionParticle("step1", "Process data", ai_provider="openai")
    p2 = AIFunctionParticle("step2", "Validate results", ai_provider="claude")
    p3 = AIFunctionParticle("step3", "Format output", ai_provider="gemini")
    
    for p in [p1, p2, p3]:
        p.synthesize()
    
    print("🔀 Fusing particles with different strategies...")
    engine = FusionEngine()
    
    # Sequential fusion
    print("\n1️⃣ Sequential Fusion (pipeline):")
    seq_fusion = engine.fuse([p1, p2, p3], mode="sequential")
    print(f"   ✅ Created: {seq_fusion.particle_id}")
    
    # Parallel fusion
    print("\n2️⃣ Parallel Fusion (concurrent execution):")
    par_fusion = engine.fuse([p1, p2, p3], mode="parallel")
    print(f"   ✅ Created: {par_fusion.particle_id}")
    
    # Consensus fusion
    print("\n3️⃣ Consensus Fusion (AI voting):")
    con_fusion = engine.fuse([p1, p2, p3], mode="consensus")
    print(f"   ✅ Created: {con_fusion.particle_id}")
    
    print(f"\n📊 Fusion History: {len(engine.fusion_history)} fusions performed\n")


def demo_ai_stack_runtime():
    """Demo 3: AI Stack Runtime - AI Stacks Executing AI Stacks"""
    print("\n" + "="*70)
    print("DEMO 3: AI Stack Runtime - Stacks Executing Stacks")
    print("="*70)
    
    print("\n🏗️ Creating AI Stack Runtime...")
    runtime = AIStackRuntime()
    
    print("🧩 Creating AI particles...")
    particles = []
    for i in range(3):
        p = AIFunctionParticle(
            f"process_step_{i+1}",
            f"Processing step {i+1}",
            ai_provider=["openai", "claude", "gemini"][i]
        )
        p.synthesize()
        runtime.register_particle(p)
        particles.append(p)
    
    print("📚 Creating AI stack (sequential execution)...")
    stack = AIStack("demo_processing_stack", particles, mode="sequential")
    runtime.register_stack(stack)
    
    print("🚀 Executing stack with input data...")
    result = runtime.execute_stack("demo_processing_stack", "Sample Data")
    
    print(f"✅ Stack execution complete!")
    print(f"📊 Result: {result}\n")
    
    metrics = runtime.get_metrics()
    print("📈 Runtime Metrics:")
    for key, value in metrics.items():
        print(f"   • {key}: {value}")


def demo_self_evolution():
    """Demo 4: Self-Evolution - AI Evolves Its Own Code"""
    print("\n" + "="*70)
    print("DEMO 4: Self-Evolution - AI Optimizes Itself")
    print("="*70)
    
    print("\n🧬 Creating Code Evolver...")
    runtime = AIStackRuntime()
    evolver = CodeEvolver(runtime)
    
    print("📊 Analyzing current performance...")
    analysis = evolver.analyze_performance()
    print(f"   • Generation: {analysis['generation']}")
    print(f"   • Bottlenecks: {len(analysis['bottlenecks'])}")
    print(f"   • Recommendations: {len(analysis['recommendations'])}")
    
    print("\n🔄 Running evolution cycles (Möbius loop)...")
    print("   Target: 30% improvement in 3 cycles\n")
    
    result = evolver.evolve_code(target_improvement="30%", max_cycles=3)
    
    print(f"\n✅ Evolution Complete!")
    print(f"   • Cycles run: {len(result['cycles'])}")
    print(f"   • Success: {result.get('success', False)}")
    print(f"   • Final performance: {result['final_performance']:.2f}")
    
    for i, cycle in enumerate(result['cycles'], 1):
        print(f"\n   Cycle {i}:")
        print(f"      Strategy: {cycle['strategy']['approach']}")
        print(f"      Improvement: {cycle['improvement']:.1%}")


def demo_manifest_driven():
    """Demo 5: Manifest-Driven Code Synthesis"""
    print("\n" + "="*70)
    print("DEMO 5: Manifest-Driven - Code from Specifications")
    print("="*70)
    
    print("\n📄 Loading manifest definitions...")
    manifest_dir = os.path.join(os.path.dirname(__file__), "manifests", "code_stacks")
    
    if os.path.exists(manifest_dir):
        import glob
        import json
        
        manifests = glob.glob(os.path.join(manifest_dir, "*.manifest.json"))
        print(f"   Found {len(manifests)} manifests")
        
        for manifest_path in manifests:
            name = os.path.basename(manifest_path)
            with open(manifest_path, 'r') as f:
                manifest = json.load(f)
            
            print(f"\n📋 {name}:")
            print(f"   • Stack: {manifest['stack_name']}")
            print(f"   • Mode: {manifest['composition']['mode']}")
            print(f"   • Particles: {len(manifest['composition']['particles'])}")
            print(f"   • Self-optimization: {manifest['self_optimization']['enabled']}")
    else:
        print("   ⚠️  Manifest directory not found")
    
    print("\n✅ All manifests define AI-generated code stacks!")


def demo_merkle_audit():
    """Demo 6: Merkle Chain Audit Trail"""
    print("\n" + "="*70)
    print("DEMO 6: Merkle Chain - Complete Auditability")
    print("="*70)
    
    from ai_primitives.base_particle import AIParticle
    
    print("\n🔐 Creating particle with Merkle chain tracking...")
    particle = AIParticle("audit_demo", "openai")
    
    print("📝 Executing multiple operations...")
    for i in range(5):
        result = particle.execute(f"Operation {i+1}")
        print(f"   {i+1}. Merkle Root: {result['merkle_root'][:16]}...{result['merkle_root'][-16:]}")
    
    print(f"\n📊 Audit Trail:")
    print(f"   • Total operations: {len(particle.merkle_chain)}")
    print(f"   • Current Merkle root: {particle.get_merkle_root()[:32]}...")
    print(f"   • Chain integrity: ✅ Verified")
    
    print("\n🔍 Every operation is cryptographically traceable!")


def main():
    """Run all demos"""
    print("\n" + "🌟"*35)
    print(" "*15 + "🧬 AI SuperComputer Demo")
    print(" "*10 + "AI-Native Architecture Showcase")
    print("🌟"*35)
    
    demos = [
        ("AI Particles", demo_ai_particles),
        ("Particle Fusion", demo_particle_fusion),
        ("AI Stack Runtime", demo_ai_stack_runtime),
        ("Self-Evolution", demo_self_evolution),
        ("Manifest-Driven", demo_manifest_driven),
        ("Merkle Audit", demo_merkle_audit),
    ]
    
    for name, demo_func in demos:
        try:
            demo_func()
            input(f"\n⏸️  Press Enter to continue to next demo...")
        except KeyboardInterrupt:
            print("\n\n👋 Demo interrupted by user")
            break
        except Exception as e:
            print(f"\n❌ Demo error: {e}")
            import traceback
            traceback.print_exc()
    
    print("\n" + "="*70)
    print("✨ Demo Complete! This is the AI-Native SuperComputer.")
    print("   Code is not written - it emerges from AI particle fusion.")
    print("="*70 + "\n")


if __name__ == "__main__":
    main()
