/*
 * C HTTP API for Hello World task
 * Generated by FlowAgent task system
 * Task ID: hello-world-api-c
 * Description: 用 C 語言寫一個 Hello World API，輸出 "你好，世界"
 *
 * Build: gcc -o hello_api hello_api.c
 * Run:   ./hello_api [port]   (default port: 5000)
 *
 * Endpoints:
 *   GET /        - Returns hello world message in Chinese
 *   GET /health  - Health check endpoint
 *   GET /info    - API information
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <signal.h>

#define DEFAULT_PORT 5000
#define BACKLOG      16
#define BUF_SIZE     4096

static int server_fd = -1;

static void handle_sigint(int sig) {
    (void)sig;
    if (server_fd >= 0) close(server_fd);
    printf("\nServer stopped.\n");
    exit(0);
}

/* Send a complete HTTP/1.1 response */
static void send_response(int client_fd, int status_code,
                          const char *status_text,
                          const char *body) {
    char header[512];
    int body_len = (int)strlen(body);
    int hlen = snprintf(header, sizeof(header),
        "HTTP/1.1 %d %s\r\n"
        "Content-Type: application/json; charset=utf-8\r\n"
        "Content-Length: %d\r\n"
        "Connection: close\r\n"
        "\r\n",
        status_code, status_text, body_len);
    write(client_fd, header, hlen);
    write(client_fd, body, body_len);
}

/* Route: GET / */
static void route_root(int client_fd) {
    const char *body = "{\"message\": \"\xe4\xbd\xa0\xe5\xa5\xbd\xef\xbc\x8c\xe4\xb8\x96\xe7\x95\x8c\"}";
    /* UTF-8 bytes above spell out: 你好，世界 */
    send_response(client_fd, 200, "OK", body);
}

/* Route: GET /health */
static void route_health(int client_fd) {
    const char *body =
        "{\"status\": \"healthy\", \"service\": \"hello-world-api-c\"}";
    send_response(client_fd, 200, "OK", body);
}

/* Route: GET /info */
static void route_info(int client_fd) {
    const char *body =
        "{"
        "\"task_id\": \"hello-world-api-c\","
        "\"language\": \"c\","
        "\"description\": \"\xe7\x94\xa8 C \xe8\xaa\x9e\xe8\xa8\x80\xe5\xaf\xab\xe4\xb8\x80\xe5\x80\x8b Hello World API\","
        "\"endpoints\": {"
            "\"/\": \"Returns hello world message in Chinese\","
            "\"/health\": \"Health check endpoint\","
            "\"/info\": \"API information\""
        "}"
        "}";
    send_response(client_fd, 200, "OK", body);
}

/* Route: 404 */
static void route_not_found(int client_fd) {
    const char *body = "{\"error\": \"Not Found\"}";
    send_response(client_fd, 404, "Not Found", body);
}

/* Parse the request line and dispatch to the correct route */
static void handle_request(int client_fd) {
    char buf[BUF_SIZE];
    ssize_t n = recv(client_fd, buf, sizeof(buf) - 1, 0);
    if (n <= 0) return;
    buf[n] = '\0';

    /* We only care about GET requests */
    if (strncmp(buf, "GET ", 4) != 0) {
        const char *body = "{\"error\": \"Method Not Allowed\"}";
        send_response(client_fd, 405, "Method Not Allowed", body);
        return;
    }

    /* Extract path (second token in request line) */
    char method[8], path[256], proto[16];
    if (sscanf(buf, "%7s %255s %15s", method, path, proto) < 2) {
        route_not_found(client_fd);
        return;
    }

    if (strcmp(path, "/") == 0) {
        route_root(client_fd);
    } else if (strcmp(path, "/health") == 0) {
        route_health(client_fd);
    } else if (strcmp(path, "/info") == 0) {
        route_info(client_fd);
    } else {
        route_not_found(client_fd);
    }
}

int main(int argc, char *argv[]) {
    int port = DEFAULT_PORT;
    if (argc >= 2) port = atoi(argv[1]);

    signal(SIGINT, handle_sigint);

    server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0) { perror("socket"); return 1; }

    int opt = 1;
    setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family      = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port        = htons((uint16_t)port);

    if (bind(server_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind"); close(server_fd); return 1;
    }
    if (listen(server_fd, BACKLOG) < 0) {
        perror("listen"); close(server_fd); return 1;
    }

    printf("hello-world-api-c listening on http://0.0.0.0:%d\n", port);
    printf("  GET /        -> {\"message\": \"你好，世界\"}\n");
    printf("  GET /health  -> health check\n");
    printf("  GET /info    -> API info\n");
    printf("Press Ctrl+C to stop.\n\n");

    while (1) {
        struct sockaddr_in client_addr;
        socklen_t client_len = sizeof(client_addr);
        int client_fd = accept(server_fd,
                               (struct sockaddr *)&client_addr,
                               &client_len);
        if (client_fd < 0) continue;

        handle_request(client_fd);
        close(client_fd);
    }

    close(server_fd);
    return 0;
}
