"""
Flask API for Hello World task
Generated by FlowAgent task system
Task ID: hello-world-api
Description: 寫一個 Flask 的 hello world API，輸出 "你好，世界"
"""

from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/')
def hello_world():
    """Return the Chinese hello world message"""
    return jsonify({"message": "你好，世界"})

@app.route('/health')
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "healthy", "service": "hello-world-api"})

@app.route('/info')
def info():
    """API information endpoint"""
    return jsonify({
        "task_id": "hello-world-api",
        "description": "寫一個 Flask 的 hello world API，輸出 \"你好，世界\"",
        "endpoints": {
            "/": "Returns hello world message in Chinese",
            "/health": "Health check endpoint", 
            "/info": "API information"
        }
    })

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)