"""
AI Class Particle - A class that is defined by AI
AI 類別粒子 - 由 AI 定義的類別

Classes in the AI SuperComputer are AI-generated based on specifications.
"""

from typing import Any, Dict, List, Optional
from .base_particle import AIParticle
from .function_particle import AIFunctionParticle


class AIClassParticle(AIParticle):
    """
    A class that is defined by AI, not hardcoded
    由 AI 定義的類別，非硬編碼
    
    Instead of writing class code, describe what the class should do,
    and AI generates the implementation with methods and properties.
    """
    
    def __init__(
        self,
        class_name: str,
        description: str,
        ai_provider: Optional[str] = None,
        methods: Optional[List[Dict]] = None,
        properties: Optional[List[Dict]] = None
    ):
        """
        Initialize AI Class Particle
        
        Args:
            class_name: Name of the class
            description: What the class should do
            ai_provider: AI provider for generation
            methods: List of method specifications
            properties: List of property specifications
        """
        super().__init__(f"class_{class_name}", ai_provider)
        self.class_name = class_name
        self.description = description
        self.methods = methods or []
        self.properties = properties or []
        self.implementation = None
        self.method_particles = []
        
    def synthesize(self, ai_provider: Optional[str] = None) -> str:
        """
        AI generates the class implementation
        AI 生成類別實現
        
        Args:
            ai_provider: Optional override for AI provider
            
        Returns:
            Generated class code
        """
        provider = ai_provider or self.provider
        
        # Generate each method as an AI function particle
        for method_spec in self.methods:
            method_particle = AIFunctionParticle(
                function_name=method_spec.get("name", "method"),
                description=method_spec.get("description", ""),
                ai_provider=provider,
                parameters=method_spec.get("parameters", {})
            )
            method_particle.synthesize()
            self.method_particles.append(method_particle)
        
        # Build complete class code
        self.implementation = self._build_class_code()
        
        return self.implementation
    
    def _build_class_code(self) -> str:
        """Build complete class code from specifications"""
        code_lines = [
            f'class {self.class_name}:',
            f'    """',
            f'    {self.description}',
            f'    ',
            f'    Auto-generated by AI ({self.provider})',
            f'    """',
            ''
        ]
        
        # Add __init__ method
        init_params = ", ".join(
            [prop.get("name", "param") for prop in self.properties]
        ) if self.properties else ""
        
        code_lines.append(f'    def __init__(self{", " + init_params if init_params else ""}):')
        code_lines.append(f'        """Initialize {self.class_name}"""')
        
        for prop in self.properties:
            prop_name = prop.get("name", "property")
            code_lines.append(f'        self.{prop_name} = {prop_name}')
        
        code_lines.append('')
        
        # Add methods
        for method_particle in self.method_particles:
            method_code = method_particle.to_code()
            # Indent method code for class
            indented_method = '\n'.join(
                '    ' + line if line.strip() else ''
                for line in method_code.split('\n')
            )
            code_lines.append(indented_method)
            code_lines.append('')
        
        return '\n'.join(code_lines)
    
    def to_code(self) -> str:
        """Export the AI-generated class code"""
        if not self.implementation:
            self.synthesize()
        return self.implementation
    
    def instantiate(self, *args, **kwargs) -> Any:
        """
        Create an instance of the AI-generated class
        創建 AI 生成類別的實例
        
        Returns:
            Instance of the generated class
        """
        if not self.implementation:
            self.synthesize()
        
        # Execute class definition
        namespace = {}
        exec(self.implementation, namespace)
        
        # Get class from namespace
        cls = namespace.get(self.class_name)
        if not cls:
            raise RuntimeError(f"Class {self.class_name} not found in generated code")
        
        # Create and return instance
        return cls(*args, **kwargs)
    
    def to_dict(self) -> Dict[str, Any]:
        """Export class particle state"""
        base_dict = super().to_dict()
        base_dict.update({
            "class_name": self.class_name,
            "description": self.description,
            "method_count": len(self.methods),
            "property_count": len(self.properties),
            "implementation": self.implementation
        })
        return base_dict
    
    def __repr__(self) -> str:
        status = "synthesized" if self.implementation else "not_synthesized"
        return f"AIClassParticle(name={self.class_name}, status={status}, methods={len(self.methods)})"
